---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiod
spec:
 components:
   pilot:
     enabled: true
     k8s:
       overlays:
         - kind: Deployment
           name: istiod # https://github.com/istio/istio/issues/31076
           patches:
             - path: spec.template.spec.volumes[name:cacerts]
               value:
                 name: cacerts
                 csi:
                   driver: secrets-store.csi.k8s.io
                   readOnly: true
                   volumeAttributes:
                     secretProviderClass: "$(ISTIO_KV_NAME)-istiod-secret-provider"
