apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  annotations:
    helm.sh/hook: post-install
spec:
  template:
    spec:
      volumes:
      - name: cacerts
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "istio-mtls"
