apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: istiod
    targetRevision: "$(ISTIO_VERSION)"
  plugin:
    name: kustomized-helm
    env:
      - name: HELM_VALUES
        value: |
          targetRevision: 1.16.1

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector
      jsonPointers:
          - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-istio-system
      jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/0/failurePolicy
  project: istio
  syncPolicy:
    automated: {}
