apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/muqtadir/istio-helm.git'
    path: istio/istio-control-patch
    plugin:
      name: kustomized-helm
      env:
        - name: ARGOCD_ENV_HELM_ARGS
          value: |
            targetRevision: 1.16.1
        - name: ARGOCD_APP_NAME
          value: istiod
        - name: ARGOCD_APP_NAMESPACE
          value: istio-system          
  project: istio
  syncPolicy:
    automated: {}
