apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./all.yaml

#patchesxJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: istiod
    path: ./overlays/istio-patch.yaml
