apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./istio-control.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: istiod
    patch: |-
      - op: replace
      # EDIT of this comment on GitHub: the [name:cacerts] references does not work
      #  path: /spec/template/spec/volumes[name:cacerts]
        path: /spec/template/spec/volumes/2
        value:
          name: cacerts
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "istio-tls"
