apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-bot
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: istio-gateway
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: gateway
    targetRevision: "$(ISTIO_VERSION)"
    helm:
      valueFiles:
      - values.yaml
  project: istio
  syncPolicy:
    automated: {}
